# Generated by Django 5.2.10 on 2026-03-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahelprequest',
            name='assigned_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cahelprequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahelprequest',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahelprequest',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cahelprequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='cahelprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cahelprequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('contacted', 'Contacted'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
