# Generated by Django 5.2.10 on 2026-03-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cahelprequest_assigned_to_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_name',
            field=models.CharField(choices=[('page_view', 'Page View'), ('notice_search', 'Notice Search'), ('search_result_clicked', 'Search Result Clicked'), ('notice_detail_viewed', 'Notice Detail Viewed'), ('notice_saved', 'Notice Saved'), ('notice_unsaved', 'Notice Unsaved'), ('ca_help_submitted', 'CA Help Submitted'), ('admin_dashboard_viewed', 'Admin Dashboard Viewed'), ('admin_dashboard_heartbeat', 'Admin Dashboard Heartbeat'), ('admin_ca_request_updated', 'Admin CA Request Updated'), ('admin_feedback_updated', 'Admin Feedback Updated')], db_index=True, max_length=64),
        ),
    ]
