# Generated by Django 5.2.10 on 2026-03-27 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_analyticsevent_event_name'),
        ('notices', '0006_noticetype_meta_description_noticetype_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('target_severity', models.CharField(choices=[('all', 'All'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('week_end', models.DateField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_name',
            field=models.CharField(choices=[('page_view', 'Page View'), ('search_performed', 'Search Performed'), ('notice_opened', 'Notice Opened'), ('ca_help_started', 'CA Help Started'), ('search_result_clicked', 'Search Result Clicked'), ('notice_saved', 'Notice Saved'), ('notice_unsaved', 'Notice Unsaved'), ('ca_help_submitted', 'CA Help Submitted'), ('assisted_offer_seen', 'Assisted Offer Seen'), ('assisted_offer_clicked', 'Assisted Offer Clicked'), ('admin_dashboard_viewed', 'Admin Dashboard Viewed'), ('admin_dashboard_heartbeat', 'Admin Dashboard Heartbeat'), ('admin_ca_request_updated', 'Admin CA Request Updated'), ('admin_feedback_updated', 'Admin Feedback Updated')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='AssistedIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('notice_code_snapshot', models.CharField(blank=True, max_length=80)),
                ('severity_snapshot', models.CharField(blank=True, max_length=20)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('experiment_key', models.CharField(blank=True, max_length=80)),
                ('experiment_variant', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('operator_notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_intents', to='notices.noticetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_intents', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intents', to='accounts.assistedoffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('experiment_key', models.CharField(db_index=True, max_length=80)),
                ('variant', models.CharField(max_length=40)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session_id', 'experiment_key')},
            },
        ),
    ]
