# Generated by Django 5.2.10 on 2026-03-30 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_payment_plan(apps, schema_editor):
    PaymentPlan = apps.get_model("accounts", "PaymentPlan")
    PaymentPlan.objects.get_or_create(
        key="single_use_notice_parse",
        defaults={
            "name": "Single Notice Parse",
            "description": "Upload one tax notice and unlock one parser result.",
            "amount_paise": 900,
            "currency": "INR",
            "credits": 1,
            "is_active": True,
            "is_default": True,
        },
    )


def reverse_default_payment_plan(apps, schema_editor):
    PaymentPlan = apps.get_model("accounts", "PaymentPlan")
    PaymentPlan.objects.filter(key="single_use_notice_parse").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_assistedoffer_weeklykpisnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amount_paise', models.PositiveIntegerField(default=900)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('credits', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['amount_paise', 'key'],
            },
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_name',
            field=models.CharField(choices=[('page_view', 'Page View'), ('search_performed', 'Search Performed'), ('notice_opened', 'Notice Opened'), ('ca_help_started', 'CA Help Started'), ('search_result_clicked', 'Search Result Clicked'), ('notice_saved', 'Notice Saved'), ('notice_unsaved', 'Notice Unsaved'), ('ca_help_submitted', 'CA Help Submitted'), ('assisted_offer_seen', 'Assisted Offer Seen'), ('assisted_offer_clicked', 'Assisted Offer Clicked'), ('payment_plan_viewed', 'Payment Plan Viewed'), ('payment_order_created', 'Payment Order Created'), ('payment_checkout_opened', 'Payment Checkout Opened'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('credit_consumed', 'Credit Consumed'), ('paid_parser_result_viewed', 'Paid Parser Result Viewed'), ('admin_dashboard_viewed', 'Admin Dashboard Viewed'), ('admin_dashboard_heartbeat', 'Admin Dashboard Heartbeat'), ('admin_ca_request_updated', 'Admin CA Request Updated'), ('admin_feedback_updated', 'Admin Feedback Updated')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('provider', models.CharField(default='cashfree', max_length=40)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payment_session_id', models.CharField(blank=True, max_length=180)),
                ('checkout_url', models.URLField(blank=True)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('credits', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('created', 'Created'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('credit_granted_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.paymentplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider_status', models.CharField(blank=True, max_length=60)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.paymentorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_credits', models.PositiveIntegerField(default=0)),
                ('lifetime_purchased_credits', models.PositiveIntegerField(default=0)),
                ('lifetime_consumed_credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RunPython(create_default_payment_plan, reverse_default_payment_plan),
    ]
