# Generated by Django 5.2.10 on 2026-02-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticetype',
            name='plain_english_explanation',
        ),
        migrations.AddField(
            model_name='noticetype',
            name='common_mistakes',
            field=models.TextField(blank=True, help_text='What do people usually do wrong?'),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='detailed_explanation',
            field=models.TextField(default='', help_text='Full deep-dive explanation (Not searchable)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticetype',
            name='source_section',
            field=models.CharField(blank=True, help_text='e.g. CGST Act Section 61', max_length=100),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='summary',
            field=models.TextField(blank=True, help_text='2-3 sentence overview (Searchable)'),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='why_received',
            field=models.TextField(blank=True, help_text='Why did I get this? (Emotional context)'),
        ),
    ]
