# Generated by Django 5.2.10 on 2026-02-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_noticetype_plain_english_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='Did this help? (Yes/No)')),
                ('comments', models.TextField(blank=True, help_text='Optional comments (only if No)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='notices.noticetype')),
            ],
        ),
    ]
