# Generated by Django 5.2.10 on 2026-02-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., GST-ASMT-10', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Official title of the notice', max_length=200)),
                ('plain_english_explanation', models.TextField(help_text='The human-friendly explanation')),
                ('consequences_of_ignoring', models.TextField(help_text='What happens if the user does nothing?')),
                ('next_steps', models.TextField(help_text='Bulleted list of immediate next steps')),
                ('severity', models.CharField(choices=[('low', 'Low - Informational'), ('medium', 'Medium - Action Required'), ('high', 'High - Urgent / Penalty Risk')], default='medium', max_length=10)),
                ('verified_by', models.CharField(blank=True, help_text='Name of the expert who verified this', max_length=100, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only active notices are shown to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword or phrase that identifies this notice', max_length=100)),
                ('notice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='notices.noticetype')),
            ],
        ),
    ]
