# Generated by Django 5.2.10 on 2026-03-27 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_noticefeedback_internal_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticetype',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ParserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('review_required', 'Review Required'), ('failed', 'Failed')], db_index=True, default='queued', max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_private_beta', models.BooleanField(default=True)),
                ('delete_after', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parser_jobs', to='notices.noticetype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parser_jobs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parser_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParserExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('legal_section', models.CharField(blank=True, max_length=120)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notice_type_detected', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0.0)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('raw_text_excerpt', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extractions', to=settings.AUTH_USER_MODEL)),
                ('parser_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='notices.parserjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
