# Generated by Django 5.2.10 on 2026-03-27 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_noticetype_meta_description_noticetype_meta_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserBenchmarkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('notice_precision', models.FloatField(default=0.0)),
                ('notice_recall', models.FloatField(default=0.0)),
                ('section_precision', models.FloatField(default=0.0)),
                ('section_recall', models.FloatField(default=0.0)),
                ('amount_precision', models.FloatField(default=0.0)),
                ('amount_recall', models.FloatField(default=0.0)),
                ('overall_f1', models.FloatField(default=0.0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parser_benchmark_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
