# Generated by Django 5.2.10 on 2026-04-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_parserbenchmarkrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='savednotice',
            name='action_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='savednotice',
            name='ca_brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savednotice',
            name='next_steps_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='savednotice',
            name='parser_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_entries', to='notices.parserjob'),
        ),
        migrations.AddField(
            model_name='savednotice',
            name='parser_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savednotice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
