# Generated by Django 5.2.10 on 2026-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_savednotice_action_status_savednotice_ca_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticetype',
            name='review_status',
            field=models.CharField(choices=[('watch', 'Watch'), ('trusted', 'Trusted'), ('needs_review', 'Needs Review')], db_index=True, default='watch', max_length=20),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='source_check_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='source_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='source_last_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='source_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticetype',
            name='source_url',
            field=models.URLField(blank=True, help_text='Official source or reference page used to monitor this notice'),
        ),
    ]
